In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from mlxtend.evaluate import bias_variance_decomp
from sklearn.neural_network import MLPClassifier
%matplotlib inline

In [2]:
train=pd.read_csv("./train.csv")
train.head()

,Id,Category,Pixel000,Pixel001,Pixel002,Pixel003,Pixel004,Pixel005,Pixel006,Pixel007,...,Pixel774,Pixel775,Pixel776,Pixel777,Pixel778,Pixel779,Pixel780,Pixel781,Pixel782,Pixel783
0,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,6,0,0,0,0,0,0,0,5,...,0,0,0,30,43,0,0,0,0,0
3,3,0,0,0,0,1,2,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,4,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test=pd.read_csv("./test.csv")
test.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_=train.drop(["Id"], axis=1)
train_.head()

,Category,Pixel000,Pixel001,Pixel002,Pixel003,Pixel004,Pixel005,Pixel006,Pixel007,Pixel008,...,Pixel774,Pixel775,Pixel776,Pixel777,Pixel778,Pixel779,Pixel780,Pixel781,Pixel782,Pixel783
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# let test and train's column name be the same
columns_name=list(train_.columns)
test.columns=columns_name
test.head()

,Category,Pixel000,Pixel001,Pixel002,Pixel003,Pixel004,Pixel005,Pixel006,Pixel007,Pixel008,...,Pixel774,Pixel775,Pixel776,Pixel777,Pixel778,Pixel779,Pixel780,Pixel781,Pixel782,Pixel783
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
X_train=train_.drop(["Category"],axis=1)
y_train=train_["Category"]
X_test=test.drop(["Category"],axis=1)
y_test=test["Category"]
#print(X_train)
#print(y_train)
#print(X_test)
#print(y_test)

In [7]:
hidden_layers=[1,2,3]
hidden_nodes=[50,200,784]
optimizers=['adam','sgd']
learning_rate_init=None
for i in range(2):
    for j in range(3):
        if optimizers[i]=='sgd':
            learning_rate_init=0.0001
        else:
            learning_rate_init=0.001
        clf = MLPClassifier(hidden_layer_sizes=(hidden_nodes[j]),
                            solver=optimizers[i],early_stopping=True,
                            learning_rate_init=learning_rate_init,
                            max_iter=100).fit(X_train, y_train)
        print("# of hidden_layers=1, hidden_nodes={}, optimizer={}".format(hidden_nodes[j],optimizers[i]))
        print(f"Train Accuracy : {clf.score(X_train, y_train)}")
        print(f"Test  Accuracy : {clf.score(X_test, y_test)}")
        clf = MLPClassifier(hidden_layer_sizes=(hidden_nodes[j],hidden_nodes[j]),
                            solver=optimizers[i],
                            early_stopping=True,
                            learning_rate_init=learning_rate_init,
                            max_iter=100).fit(X_train, y_train)
        print("# of hidden_layers=2, hidden_nodes={}, optimizer={}".format(hidden_nodes[j],optimizers[i]))
        print(f"Train Accuracy : {clf.score(X_train, y_train)}")
        print(f"Test  Accuracy : {clf.score(X_test, y_test)}")
        clf = MLPClassifier(hidden_layer_sizes=(hidden_nodes[j],hidden_nodes[j],hidden_nodes[j]),
                            solver=optimizers[i],
                            early_stopping=True,
                            learning_rate_init=learning_rate_init,
                            max_iter=100).fit(X_train, y_train)
        print("# of hidden_layers=3, hidden_nodes={}, optimizer={}".format(hidden_nodes[j],optimizers[i]))
        print(f"Train Accuracy : {clf.score(X_train, y_train)}")
        print(f"Test  Accuracy : {clf.score(X_test, y_test)}")

# of hidden_layers=1, hidden_nodes=50, optimizer=adam
Train Accuracy : 0.8774166666666666
Test  Accuracy : 0.8582
# of hidden_layers=2, hidden_nodes=50, optimizer=adam
Train Accuracy : 0.8715833333333334
Test  Accuracy : 0.8568
# of hidden_layers=3, hidden_nodes=50, optimizer=adam
Train Accuracy : 0.8954333333333333
Test  Accuracy : 0.8716
# of hidden_layers=1, hidden_nodes=200, optimizer=adam
Train Accuracy : 0.8970333333333333
Test  Accuracy : 0.8734
# of hidden_layers=2, hidden_nodes=200, optimizer=adam
Train Accuracy : 0.92585
Test  Accuracy : 0.8844
# of hidden_layers=3, hidden_nodes=200, optimizer=adam
Train Accuracy : 0.9347833333333333
Test  Accuracy : 0.8917
# of hidden_layers=1, hidden_nodes=784, optimizer=adam
Train Accuracy : 0.8924666666666666
Test  Accuracy : 0.8634
# of hidden_layers=2, hidden_nodes=784, optimizer=adam
Train Accuracy : 0.9047666666666667
Test  Accuracy : 0.8764
# of hidden_layers=3, hidden_nodes=784, optimizer=adam
Train Accuracy : 0.9176833333333333
Test  Accuracy : 0.8852
# of hidden_layers=1, hidden_nodes=50, optimizer=sgd
Train Accuracy : 0.7422
Test  Accuracy : 0.7263

/Users/yangjinglan/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

# of hidden_layers=2, hidden_nodes=50, optimizer=sgd
Train Accuracy : 0.8720666666666667
Test  Accuracy : 0.8549
# of hidden_layers=3, hidden_nodes=50, optimizer=sgd
Train Accuracy : 0.8691166666666666
Test  Accuracy : 0.8592
# of hidden_layers=1, hidden_nodes=200, optimizer=sgd
Train Accuracy : 0.8659
Test  Accuracy : 0.845
# of hidden_layers=2, hidden_nodes=200, optimizer=sgd
Train Accuracy : 0.91115
Test  Accuracy : 0.8592
# of hidden_layers=3, hidden_nodes=200, optimizer=sgd
Train Accuracy : 0.9164333333333333
Test  Accuracy : 0.865
# of hidden_layers=1, hidden_nodes=784, optimizer=sgd
Train Accuracy : 0.9214166666666667
Test  Accuracy : 0.8675
# of hidden_layers=2, hidden_nodes=784, optimizer=sgd
Train Accuracy : 0.9525833333333333
Test  Accuracy : 0.868
# of hidden_layers=3, hidden_nodes=784, optimizer=sgd
Train Accuracy : 0.9794
Test  Accuracy : 0.8694